"""Generate browser ESM wrappers for rich Multilingual Python output.

This bridge is intentionally JSON-first: it serves programs whose exported
functions return ordinary Python values that map cleanly to JavaScript through
Pyodide, while the WAT/WASM backend continues to serve narrow numeric ABIs.
"""

from __future__ import annotations

import json
from collections.abc import Iterable

from multilingualprogramming.codegen.python_generator import PythonCodeGenerator


def _js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate_browser_module(
    program,
    *,
    exports: Iterable[str] | None = None,
    stub_modules: Iterable[str] | None = None,
) -> str:
    """Return an ESM module that exposes selected .multi functions in browsers."""

    python_source = PythonCodeGenerator().generate(program)
    export_names = list(exports or [])
    stub_module_names = list(stub_modules or [])
    export_set_literal = json.dumps(export_names, ensure_ascii=False)
    stub_modules_literal = json.dumps(stub_module_names, ensure_ascii=False)

    export_lines: list[str] = []
    for name in export_names:
        export_lines.append(
            f"export async function {name}(...args) {{\n"
            f"  return callMultilingualFunction({_js_string(name)}, args);\n"
            f"}}"
        )

    if not export_lines:
        export_lines.append(
            "export async function call(name, ...args) {\n"
            "  return callMultilingualFunction(name, args);\n"
            "}"
        )

    return "\n".join(
        [
            "// Generated by multilingualprogramming build-browser-module.",
            "// Loads rich .multi output through Pyodide so JSON-like lists/dicts",
            "// can be used in static browser applications.",
            "",
            f"const PYTHON_SOURCE = {_js_string(python_source)};",
            f"const DECLARED_EXPORTS = new Set({export_set_literal});",
            f"const STUB_MODULES = {stub_modules_literal};",
            "let runtimePromise = null;",
            "",
            "async function ensurePyodideRuntime() {",
            "  if (runtimePromise) return runtimePromise;",
            "  runtimePromise = (async () => {",
            "    if (typeof globalThis.loadPyodide !== \"function\") {",
            "      throw new Error(\"loadPyodide is required before using this Multilingual browser module\");",
            "    }",
            "    const pyodide = await globalThis.loadPyodide();",
            "    const globals = pyodide.toPy({});",
            "    if (STUB_MODULES.length) {",
            "      globals.set(\"__ml_stub_modules\", pyodide.toPy(STUB_MODULES));",
            "      pyodide.runPython(",
            "        \"import sys, types\\n\" +",
            "        \"for name in __ml_stub_modules:\\n\" +",
            "        \"    sys.modules.setdefault(name, types.ModuleType(name))\",",
            "        { globals },",
            "      );",
            "    }",
            "    pyodide.runPython(PYTHON_SOURCE, { globals });",
            "    return { pyodide, globals };",
            "  })();",
            "  return runtimePromise;",
            "}",
            "",
            "function toJs(value) {",
            "  if (value && typeof value.toJs === \"function\") {",
            "    return value.toJs({ dict_converter: Object.fromEntries });",
            "  }",
            "  return value;",
            "}",
            "",
            "async function callMultilingualFunction(name, args) {",
            "  if (DECLARED_EXPORTS.size && !DECLARED_EXPORTS.has(name)) {",
            "    throw new Error(`Function ${name} was not exported by this module`);",
            "  }",
            "  const { pyodide, globals } = await ensurePyodideRuntime();",
            "  const fn = globals.get(name);",
            "  if (typeof fn !== \"function\") {",
            "    throw new Error(`Generated Multilingual function not found: ${name}`);",
            "  }",
            "  try {",
            "    return toJs(fn(...args));",
            "  } finally {",
            "    if (fn && typeof fn.destroy === \"function\") fn.destroy();",
            "  }",
            "}",
            "",
            "export async function ready() {",
            "  await ensurePyodideRuntime();",
            "}",
            "",
            *export_lines,
            "",
        ]
    )
