"""JavaScript code generator for browser-native Multilingual modules.

This generator intentionally starts with a conservative, pure-data subset:
functions, loops, conditionals, JSON-like values, comprehensions, and common
Python-style helpers used by generated Multilingual browser integrations.
Unsupported syntax raises loudly instead of silently changing semantics.
"""

from __future__ import annotations

import json

from multilingualprogramming.exceptions import CodeGenerationError
from multilingualprogramming.numeral.mp_numeral import MPNumeral
from multilingualprogramming.parser.ast_nodes import (
    AttributeAccess,
    Identifier,
    StringLiteral,
)


def _convert_numeral_literal(raw_value):
    try:
        num = MPNumeral(raw_value)
        decimal = num.to_decimal()
        if isinstance(decimal, float):
            return repr(decimal)
        return str(decimal)
    except Exception:
        try:
            if isinstance(raw_value, str) and raw_value.lower().startswith(
                ("0x", "0o", "0b")
            ):
                return str(int(raw_value, 0))
            return str(int(raw_value))
        except ValueError:
            try:
                return repr(float(raw_value))
            except ValueError:
                return raw_value


class JavaScriptCodeGenerator:
    """Generate browser-native JavaScript from a Multilingual AST."""

    def __init__(self, indent_str: str = "  ", exports=None):
        self.indent_str = indent_str
        self.exports = set(exports or [])
        self._depth = 0
        self._lines: list[str] = []
        self._function_names: set[str] = set()

    def generate(self, node) -> str:
        """Generate JavaScript source for a parsed program node."""
        self._depth = 0
        self._lines = []
        self._function_names = {
            stmt.name
            for stmt in getattr(node, "body", [])
            if type(stmt).__name__ == "FunctionDef"
        }
        self._emit_runtime()
        node.accept(self)
        self._emit_exports()
        return "\n".join(self._lines) + "\n"

    def _emit(self, text: str = "") -> None:
        self._lines.append((self.indent_str * self._depth) + text)

    def _indent(self) -> None:
        self._depth += 1

    def _dedent(self) -> None:
        self._depth -= 1

    def _expr(self, node) -> str:
        return node.accept(_JSExpressionGenerator(self._function_names))

    def _target(self, node) -> str:
        return self._expr(node)

    def _param(self, node) -> str:
        if isinstance(node, str):
            return node
        name = getattr(node, "name", str(node))
        if getattr(node, "default", None) is not None:
            return f"{name} = {self._expr(node.default)}"
        return name

    def _error(self, message: str, node) -> None:
        raise CodeGenerationError(message, getattr(node, "line", 0), getattr(node, "column", 0))

    def _emit_runtime(self) -> None:
        self._emit("// Generated by multilingualprogramming build-browser-module.")
        self._emit("const __ml = {")
        self._indent()
        self._emit("len: (value) => value == null ? 0 : value.length ?? Object.keys(value).length,")
        self._emit("str: (value) => String(value),")
        self._emit("int: (value) => Number.parseInt(value, 10),")
        self._emit("float: (value) => Number.parseFloat(value),")
        self._emit("list: (value) => Array.isArray(value) ? [...value] : Array.from(value),")
        self._emit("dict: (value = {}) => ({ ...value }),")
        self._emit("set: (value = []) => new Set(value),")
        self._emit("range: (start, stop, step = 1) => {")
        self._indent()
        self._emit("if (stop === undefined) { stop = start; start = 0; }")
        self._emit("const out = [];")
        self._emit("if (step === 0) throw new Error('range() step cannot be zero');")
        self._emit("if (step > 0) { for (let i = start; i < stop; i += step) out.push(i); }")
        self._emit("else { for (let i = start; i > stop; i += step) out.push(i); }")
        self._emit("return out;")
        self._dedent()
        self._emit("},")
        self._emit(
            "max: (...args) => "
            "Math.max(...(args.length === 1 && Array.isArray(args[0]) ? args[0] : args)),"
        )
        self._emit(
            "min: (...args) => "
            "Math.min(...(args.length === 1 && Array.isArray(args[0]) ? args[0] : args)),"
        )
        self._emit("sum: (values) => values.reduce((acc, value) => acc + value, 0),")
        self._emit("abs: (value) => Math.abs(value),")
        self._emit("isinstance: (value, type) => {")
        self._indent()
        self._emit("if (type === Array || type === 'list') return Array.isArray(value);")
        self._emit(
            "if (type === Object || type === 'dict') "
            "return value !== null && typeof value === 'object' && !Array.isArray(value);"
        )
        self._emit("return value instanceof type;")
        self._dedent()
        self._emit("},")
        self._emit("json_dumps: (value) => JSON.stringify(value),")
        self._emit("json_loads: (value) => JSON.parse(value),")
        self._emit(
            "get: (obj, key, fallback = undefined) => "
            "Object.prototype.hasOwnProperty.call(obj ?? {}, key) ? obj[key] : fallback,"
        )
        self._emit("items: (obj) => Object.entries(obj ?? {}),")
        self._emit("append: (arr, value) => { arr.push(value); return undefined; },")
        self._emit(
            "contains: (container, value) => "
            "Array.isArray(container) || typeof container === 'string' "
            "? container.includes(value) "
            ": Object.prototype.hasOwnProperty.call(container ?? {}, value),"
        )
        self._emit("choice: (arr) => arr[Math.floor(Math.random() * arr.length)],")
        self._emit("random: () => Math.random(),")
        self._dedent()
        self._emit("};")
        self._emit("const json = { dumps: __ml.json_dumps, loads: __ml.json_loads };")
        self._emit("function __mlRandom(seed = Date.now()) {")
        self._indent()
        self._emit("let value = Number(seed) >>> 0;")
        self._emit("const next = () => {")
        self._indent()
        self._emit("value = (value + 0x6D2B79F5) >>> 0;")
        self._emit("let t = value;")
        self._emit("t = Math.imul(t ^ (t >>> 15), t | 1);")
        self._emit("t ^= t + Math.imul(t ^ (t >>> 7), t | 61);")
        self._emit("return ((t ^ (t >>> 14)) >>> 0) / 4294967296;")
        self._dedent()
        self._emit("};")
        self._emit("return {")
        self._indent()
        self._emit("random: next,")
        self._emit("choice: (arr) => arr[Math.floor(next() * arr.length)],")
        self._emit("randint: (a, b) => Math.floor(next() * (b - a + 1)) + a,")
        self._dedent()
        self._emit("};")
        self._dedent()
        self._emit("}")
        self._emit("const random = { random: __ml.random, choice: __ml.choice, Random: __mlRandom };")
        self._emit("const __ml_contains = __ml.contains;")
        self._emit("")

    def _emit_exports(self) -> None:
        export_names = sorted(self.exports or self._function_names)
        if export_names:
            self._emit("")
            self._emit(f"export {{ {', '.join(export_names)} }};")

    def _emit_body(self, body) -> None:
        self._indent()
        if not body:
            self._emit(";")
        else:
            for stmt in body:
                stmt.accept(self)
        self._dedent()

    def visit_Program(self, node) -> None:
        for stmt in node.body:
            stmt.accept(self)

    def visit_ImportStatement(self, node) -> None:
        self._emit(f"// import {node.module} handled by generated runtime or host")

    def visit_FromImportStatement(self, node) -> None:
        self._emit(f"// from {node.module} import ... handled by generated runtime or host")

    def visit_FunctionDef(self, node) -> None:
        params = ", ".join(self._param(param) for param in node.params)
        self._emit(f"function {node.name}({params}) {{")
        self._emit_body(node.body)
        self._emit("}")

    def visit_VariableDeclaration(self, node) -> None:
        self._emit(f"let {node.name} = {self._expr(node.value)};")

    def visit_Assignment(self, node) -> None:
        op = node.op
        self._emit(f"{self._target(node.target)} {op} {self._expr(node.value)};")

    def visit_AnnAssignment(self, node) -> None:
        if node.value is None:
            self._emit(f"let {self._target(node.target)};")
        else:
            self._emit(f"let {self._target(node.target)} = {self._expr(node.value)};")

    def visit_ExpressionStatement(self, node) -> None:
        if isinstance(node.expression, Identifier) and node.expression.name in {"rien", "pass"}:
            self._emit(";")
            return
        self._emit(f"{self._expr(node.expression)};")

    def visit_ReturnStatement(self, node) -> None:
        self._emit(f"return {self._expr(node.value) if node.value else 'undefined'};")

    def visit_PassStatement(self, _node) -> None:
        self._emit(";")

    def visit_BreakStatement(self, _node) -> None:
        self._emit("break;")

    def visit_ContinueStatement(self, _node) -> None:
        self._emit("continue;")

    def visit_IfStatement(self, node) -> None:
        self._emit(f"if ({self._expr(node.condition)}) {{")
        self._emit_body(node.body)
        for condition, body in node.elif_clauses:
            self._emit(f"}} else if ({self._expr(condition)}) {{")
            self._emit_body(body)
        if node.else_body:
            self._emit("} else {")
            self._emit_body(node.else_body)
        self._emit("}")

    def visit_ForLoop(self, node) -> None:
        self._emit(f"for (const {self._target(node.target)} of {self._expr(node.iterable)}) {{")
        self._emit_body(node.body)
        self._emit("}")

    def visit_WhileLoop(self, node) -> None:
        self._emit(f"while ({self._expr(node.condition)}) {{")
        self._emit_body(node.body)
        self._emit("}")

    def visit_RaiseStatement(self, node) -> None:
        value = self._expr(node.value) if node.value else '"Multilingual error"'
        self._emit(f"throw new Error(String({value}));")

    def visit_TryStatement(self, node) -> None:
        self._emit("try {")
        self._emit_body(node.body)
        if node.handlers:
            handler = node.handlers[0]
            name = handler.name or "_error"
            self._emit(f"}} catch ({name}) {{")
            self._emit_body(handler.body)
        else:
            self._emit("} catch (_error) {")
            self._indent()
            self._emit("throw _error;")
            self._dedent()
        if node.finally_body:
            self._emit("} finally {")
            self._emit_body(node.finally_body)
        self._emit("}")

    def visit_WithStatement(self, node) -> None:
        self._emit("{")
        self._indent()
        for context_expr, name in node.items:
            expr = self._expr(context_expr)
            if name:
                self._emit(f"const {name} = {expr};")
            else:
                self._emit(f"{expr};")
        for stmt in node.body:
            stmt.accept(self)
        self._dedent()
        self._emit("}")

    def visit_AssertStatement(self, node) -> None:
        message = (
            self._expr(node.message)
            if getattr(node, "message", None)
            else '"assertion failed"'
        )
        self._emit(f"if (!({self._expr(node.condition)})) throw new Error(String({message}));")

    def generic_visit(self, node) -> None:
        """Raise for unsupported statement nodes."""
        self._error(f"Unsupported JavaScript generation node: {type(node).__name__}", node)


class _JSExpressionGenerator:
    """Visitor that returns JavaScript expression strings."""

    def __init__(self, function_names: set[str] | None = None):
        self.function_names = function_names or set()

    def _expr(self, node) -> str:
        return node.accept(self)

    def _error(self, message: str, node) -> None:
        raise CodeGenerationError(message, getattr(node, "line", 0), getattr(node, "column", 0))

    def _comprehension_clauses(self, node):
        clauses = getattr(node, "clauses", None)
        return clauses or [node]

    def visit_NumeralLiteral(self, node):
        return _convert_numeral_literal(node.value)

    def visit_StringLiteral(self, node):
        return json.dumps(node.value, ensure_ascii=False)

    def visit_BooleanLiteral(self, node):
        return "true" if node.value else "false"

    def visit_NoneLiteral(self, _node):
        return "null"

    def visit_ListLiteral(self, node):
        return "[" + ", ".join(self._expr(item) for item in node.elements) + "]"

    def visit_TupleLiteral(self, node):
        return "[" + ", ".join(self._expr(item) for item in node.elements) + "]"

    def visit_DictLiteral(self, node):
        parts = []
        for entry in node.entries:
            if isinstance(entry, tuple):
                key, value = entry
                if isinstance(key, StringLiteral):
                    rendered_key = json.dumps(key.value, ensure_ascii=False)
                    parts.append(f"{rendered_key}: {self._expr(value)}")
                else:
                    parts.append(f"[{self._expr(key)}]: {self._expr(value)}")
            else:
                parts.append(f"...{self._expr(entry.value)}")
        return "{" + ", ".join(parts) + "}"

    def visit_SetLiteral(self, node):
        return f"new Set([{', '.join(self._expr(item) for item in node.elements)}])"

    def visit_DictUnpackEntry(self, node):
        return self._expr(node.value)

    def visit_Identifier(self, node):
        mapping = {
            "True": "true",
            "False": "false",
            "None": "null",
            "len": "__ml.len",
            "str": "__ml.str",
            "int": "__ml.int",
            "float": "__ml.float",
            "list": "__ml.list",
            "dict": "__ml.dict",
            "set": "__ml.set",
            "range": "__ml.range",
            "max": "__ml.max",
            "min": "__ml.min",
            "sum": "__ml.sum",
            "abs": "__ml.abs",
            "isinstance": "__ml.isinstance",
        }
        return mapping.get(node.name, node.name)

    def visit_BinaryOp(self, node):
        op = {"//": "/", "and": "&&", "or": "||"}.get(node.op, node.op)
        if node.op == "|":
            return f"new Set([...{self._expr(node.left)}, ...{self._expr(node.right)}])"
        if node.op == "//":
            return f"Math.trunc(({self._expr(node.left)}) / ({self._expr(node.right)}))"
        if node.op == "**":
            return f"(({self._expr(node.left)}) ** ({self._expr(node.right)}))"
        return f"({self._expr(node.left)} {op} {self._expr(node.right)})"

    def visit_UnaryOp(self, node):
        if node.op == "NOT":
            return f"(!{self._expr(node.operand)})"
        return f"({node.op}{self._expr(node.operand)})"

    def visit_BooleanOp(self, node):
        op = " && " if node.op == "AND" else " || "
        return "(" + op.join(self._expr(value) for value in node.values) + ")"

    def visit_CompareOp(self, node):
        left = self._expr(node.left)
        parts = []
        previous = left
        for op, right_node in node.comparators:
            right = self._expr(right_node)
            js_op = {
                "==": "===",
                "!=": "!==",
                "in": "__in__",
                "not in": "__not_in__",
                "is": "===",
                "is not": "!==",
            }.get(op, op)
            if js_op == "__in__":
                parts.append(f"__ml_contains({right}, {previous})")
            elif js_op == "__not_in__":
                parts.append(f"(!__ml_contains({right}, {previous}))")
            else:
                parts.append(f"({previous} {js_op} {right})")
            previous = right
        return "(" + " && ".join(parts) + ")"

    def visit_CallExpr(self, node):
        func = self._expr(node.func)
        if (
            isinstance(node.func, Identifier)
            and node.func.name == "isinstance"
            and len(node.args) >= 2
        ):
            value = self._expr(node.args[0])
            type_arg = node.args[1]
            if isinstance(type_arg, Identifier) and type_arg.name == "list":
                return f"__ml.isinstance({value}, Array)"
            if isinstance(type_arg, Identifier) and type_arg.name == "dict":
                return f"__ml.isinstance({value}, Object)"
        if isinstance(node.func, Identifier) and node.func.name in {"max", "min"}:
            key_expr = None
            for name, value in node.keywords:
                if name == "key":
                    key_expr = self._expr(value)
            if key_expr and node.args:
                iterable = self._expr(node.args[0])
                compare = ">" if node.func.name == "max" else "<"
                return (
                    f"Array.from({iterable}).reduce((best, item) => "
                    f"{key_expr}(item) {compare} {key_expr}(best) ? item : best)"
                )
        args = [self._expr(arg) for arg in node.args]
        if isinstance(node.func, AttributeAccess):
            obj = self._expr(node.func.obj)
            attr = node.func.attr
            if attr == "get":
                return f"__ml.get({obj}, {', '.join(args)})"
            if attr == "items":
                return f"__ml.items({obj})"
            if attr == "keys":
                return f"Object.keys({obj} ?? {{}})"
            if attr == "values":
                return f"Object.values({obj} ?? {{}})"
            if attr == "append":
                return f"__ml.append({obj}, {args[0] if args else 'undefined'})"
            if attr == "replace":
                return f"{obj}.replaceAll({', '.join(args)})"
            if attr == "join":
                return f"({args[0] if args else '[]'}).join({obj})"
            if attr == "split":
                return f"{obj}.split({args[0] if args else 'undefined'})"
            if attr == "strip":
                return f"{obj}.trim()"
            if attr == "is_integer":
                return f"Number.isInteger({obj})"
            if attr == "choice":
                if isinstance(node.func.obj, Identifier) and node.func.obj.name == "random":
                    return f"__ml.choice({args[0] if args else '[]'})"
                return f"{obj}.choice({args[0] if args else '[]'})"
            if attr == "random":
                if isinstance(node.func.obj, Identifier) and node.func.obj.name == "random":
                    return "__ml.random()"
                return f"{obj}.random()"
        return f"{func}({', '.join(args)})"

    def visit_AttributeAccess(self, node):
        obj = self._expr(node.obj)
        if isinstance(node.obj, Identifier) and node.obj.name == "json":
            json_attrs = {"dumps": "__ml.json_dumps", "loads": "__ml.json_loads"}
            return json_attrs.get(node.attr, f"json.{node.attr}")
        return f"{obj}.{node.attr}"

    def visit_IndexAccess(self, node):
        if type(node.index).__name__ == "SliceExpr":
            start = self._expr(node.index.start) if node.index.start else ""
            stop = self._expr(node.index.stop) if node.index.stop else ""
            if node.index.step is not None:
                self._error("JavaScript generator does not support slice steps yet", node.index)
            if start == "" and stop != "":
                args = f"0, {stop}"
            else:
                args = ", ".join(part for part in [start, stop] if part != "")
            return f"{self._expr(node.obj)}.slice({args})"
        return f"{self._expr(node.obj)}[{self._expr(node.index)}]"

    def visit_ConditionalExpr(self, node):
        return (
            f"({self._expr(node.condition)} ? "
            f"{self._expr(node.true_expr)} : {self._expr(node.false_expr)})"
        )

    def visit_ListComprehension(self, node):
        return self._array_comprehension(self._expr(node.element), node)

    def visit_GeneratorExpr(self, node):
        return self._array_comprehension(self._expr(node.element), node)

    def visit_SetComprehension(self, node):
        return f"new Set({self._array_comprehension(self._expr(node.element), node)})"

    def visit_DictComprehension(self, node):
        clauses = self._comprehension_clauses(node)
        if len(clauses) != 1:
            self._error("JavaScript generator supports one comprehension clause", node)
        clause = clauses[0]
        target = self._expr(clause.target)
        iterable = self._expr(clause.iterable)
        key = self._expr(node.key)
        value = self._expr(node.value)
        conditions = " && ".join(self._expr(cond) for cond in clause.conditions) or "true"
        return (
            f"Object.fromEntries(Array.from({iterable}).filter(({target}) => {conditions})"
            f".map(({target}) => [{key}, {value}]))"
        )

    def _array_comprehension(self, element: str, node):
        clauses = self._comprehension_clauses(node)
        if len(clauses) != 1:
            self._error("JavaScript generator supports one comprehension clause", node)
        clause = clauses[0]
        target = self._expr(clause.target)
        iterable = self._expr(clause.iterable)
        conditions = " && ".join(self._expr(cond) for cond in clause.conditions)
        result = f"Array.from({iterable})"
        if conditions:
            result += f".filter(({target}) => {conditions})"
        result += f".map(({target}) => {element})"
        return result

    def visit_Parameter(self, node):
        return node.name

    def visit_LambdaExpr(self, node):
        params = ", ".join(param if isinstance(param, str) else self._expr(param) for param in node.params)
        return f"(({params}) => {self._expr(node.body)})"

    def visit_SliceExpr(self, node):
        start = self._expr(node.start) if node.start else ""
        stop = self._expr(node.stop) if node.stop else ""
        return f"{start}:{stop}"

    def generic_visit(self, node):
        """Raise for unsupported expression nodes."""
        self._error(f"Unsupported JavaScript expression node: {type(node).__name__}", node)
