#
# SPDX-FileCopyrightText: 2026 John Samuel <johnsamuelwrites@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""Lower reactive Core IR into a self-contained HTML/JavaScript preview."""

# pylint: disable=too-many-return-statements,too-many-branches

from __future__ import annotations

from dataclasses import dataclass, field

from multilingualprogramming.core.ir_nodes import (
    IRAwaitExpr,
    IRAttributeAccess,
    IRBinaryOp,
    IRBooleanOp,
    IRCallExpr,
    IRCanvasBlock,
    IRCompareOp,
    IRConditionalExpr,
    IRExprStatement,
    IRForLoop,
    IRFunction,
    IRIdentifier,
    IRIfStatement,
    IRIndexAccess,
    IRLiteral,
    IRListLiteral,
    IRNode,
    IRObserveBinding,
    IROnChange,
    IRProgram,
    IRRenderBlock,
    IRReturnStatement,
    IRUIElement,
    IRUnaryOp,
    IRViewBinding,
)


@dataclass
class UILoweringResult:
    """Output of the UI lowering pass."""

    html: str = ""
    js: str = ""
    diagnostics: list[str] = field(default_factory=list)
    js_signals: list[str] = field(default_factory=list)
    js_handlers: list[str] = field(default_factory=list)
    js_bindings: list[str] = field(default_factory=list)

    def emit_html(self) -> str:
        """Return the generated HTML document."""
        return self.html

    def emit_js(self) -> str:
        """Return the generated JavaScript bundle."""
        return self.js


class UILoweringPass:
    """Lower an IR program to a browser preview bundle."""

    def __init__(self) -> None:
        self._result = UILoweringResult()
        self._signal_names: set[str] = set()
        self._render_roots: list[str] = []
        self._canvas_names: list[str] = []
        self._functions: list[str] = []
        self._render_function = ""
        self._preamble = ""

    def lower(self, program: IRProgram) -> UILoweringResult:
        """Lower an IRProgram to UI output."""
        self._emit_preamble()
        for node in program.body:
            self._lower_node(node)

        self._wire_render_updates()

        js_parts = [self._preamble]
        js_parts.extend(self._result.js_signals)
        js_parts.extend(self._functions)
        js_parts.extend(self._result.js_handlers)
        js_parts.extend(self._result.js_bindings)
        if self._render_function:
            js_parts.append(self._render_function)
            js_parts.append("if (typeof __ml_render === 'function') {\n  __ml_render();\n}")

        self._result.js = "\n\n".join(part for part in js_parts if part)
        self._result.html = self._emit_html()
        return self._result

    def _lower_node(self, node: IRNode) -> None:
        """Lower one node, descending into wrapper functions when useful."""
        if isinstance(node, IRObserveBinding):
            self._lower_observe(node)
            return
        if isinstance(node, IROnChange):
            self._lower_on_change(node)
            return
        if isinstance(node, IRCanvasBlock):
            self._lower_canvas(node)
            return
        if isinstance(node, IRViewBinding):
            self._lower_view_binding(node)
            return
        if isinstance(node, IRRenderBlock):
            self._lower_render_block(node)
            return
        if isinstance(node, IRFunction):
            if node.is_async:
                self._lower_function(node)
            else:
                for child in node.body:
                    self._lower_node(child)

    def _emit_preamble(self) -> None:
        self._preamble = """// Generated by Multilingual UI lowering
class ReactiveSignal {
  constructor(value) {
    this._value = value;
    this._handlers = [];
  }
  get() { return this._value; }
  set(value) {
    this._value = value;
    for (const handler of this._handlers) {
      handler(value);
    }
  }
  on_change(handler) {
    this._handlers.push(handler);
  }
}

class ReactiveList {
  constructor(value) {
    this._value = Array.from(value || []);
    this._handlers = [];
  }
  get() { return this._value.slice(); }
  set(value) {
    this._value = Array.from(value || []);
    this._notify();
  }
  setIndex(index, value) {
    this._value[index] = value;
    this._notify();
  }
  on_change(handler) {
    this._handlers.push(handler);
  }
  _notify() {
    const snapshot = this.get();
    for (const handler of this._handlers) {
      handler(snapshot);
    }
  }
}

class ReactiveEngine {
  constructor() {
    this.signals = {};
  }
  declare(name, initial) {
    if (!this.signals[name]) {
      this.signals[name] = __ml_signal(initial);
    }
    return this.signals[name];
  }
  get(name) {
    return this.signals[name];
  }
  on_change(name) {
    return (handler) => {
      this.declare(name, null).on_change(handler);
      return handler;
    };
  }
}

function __ml_signal(initial) {
  return Array.isArray(initial) ? new ReactiveList(initial) : new ReactiveSignal(initial);
}

function streamToView(source, target) {
  if (!source || !target || typeof source.on_change !== 'function') {
    return;
  }
  source.on_change((value) => {
    target.textContent = value == null ? '' : String(value);
  });
}

const _engine = new ReactiveEngine();
const __ml_signals = _engine.signals;"""

    def _lower_observe(self, node: IRObserveBinding) -> None:
        self._signal_names.add(node.name)
        value = self._expr_to_js(node.value)
        self._result.js_signals.append(
            f"__ml_signals['{node.name}'] = _engine.declare('{node.name}', {value});"
        )

    def _lower_on_change(self, node: IROnChange) -> None:
        signal_name = self._signal_name(node.signal) or self._expr_to_js(node.signal)
        body = "\n".join(self._stmt_to_js(stmt, 1) for stmt in (node.body or []))
        if not body:
            body = "  return undefined;"
        self._result.js_handlers.append(
            f"_engine.on_change('{signal_name}')((value) => {{\n{body}\n}});"
        )

    def _lower_canvas(self, node: IRCanvasBlock) -> None:
        self._canvas_names.append(node.name or "canvas")

    def _lower_view_binding(self, node: IRViewBinding) -> None:
        signal_name = self._signal_name(node.signal)
        target_name = self._identifier_name(node.target) or self._expr_to_js(node.target)
        if signal_name:
            self._result.js_bindings.append(
                "streamToView("
                f"_engine.get('{signal_name}'), document.getElementById('{target_name}')"
                ");"
            )

    def _lower_function(self, node: IRFunction) -> None:
        keyword = "async function" if node.is_async else "function"
        params = ", ".join(param.name for param in (node.parameters or []))
        body = "\n".join(self._stmt_to_js(stmt, 1) for stmt in (node.body or []))
        self._functions.append(f"{keyword} {node.name}({params}) {{\n{body}\n}}")

    def _lower_render_block(self, node: IRRenderBlock) -> None:
        self._render_roots.append("__ml_root")
        lines = [
            "function __ml_render() {",
            "  const __root = document.getElementById('__ml_root');",
            "  if (!__root) {",
            "    return;",
            "  }",
            "  __root.innerHTML = '';",
        ]
        if node.root is not None:
            lines.extend(self._element_to_js(node.root, "__root", 1))
        lines.append("}")
        self._render_function = "\n".join(lines)

    def _wire_render_updates(self) -> None:
        if not self._render_function:
            return
        for name in sorted(self._signal_names):
            self._result.js_handlers.append(
                f"_engine.on_change('{name}')(() => __ml_render());"
            )

    def _emit_html(self) -> str:
        canvas_html = "\n".join(
            f'    <div id="{name}" class="ml-canvas"></div>'
            for name in self._canvas_names
        )
        root_html = '    <div id="__ml_root"></div>' if self._render_roots else ""
        title = "Memory Game - Multilingual" if self._render_roots else "Multilingual UI Preview"
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    body {{
      margin: 0;
      padding: 24px;
      font-family: system-ui, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
    }}
    .ml-canvas {{
      min-height: 48px;
      border: 1px dashed #8aa;
      padding: 12px;
      margin-bottom: 12px;
    }}
    .memory-game {{
      background: white;
      border-radius: 12px;
      padding: 32px;
      box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
      max-width: 600px;
    }}
    .memory-game h1 {{
      text-align: center;
      color: #333;
      margin-top: 0;
      margin-bottom: 24px;
      font-size: 28px;
    }}
    .game-board {{
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin-bottom: 24px;
      padding: 16px;
      background: #f5f5f5;
      border-radius: 8px;
    }}
    .card {{
      aspect-ratio: 1;
      padding: 0;
      border: 2px solid #ddd;
      background: #fff;
      color: #333;
      font-size: 32px;
      font-weight: bold;
      cursor: pointer;
      border-radius: 6px;
      transition: all 0.2s ease;
    }}
    .card:hover {{
      transform: scale(1.05);
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }}
    .card:disabled {{
      opacity: 0.6;
      cursor: not-allowed;
    }}
    .card.revealed {{
      background: #e3f2fd;
      border-color: #2196f3;
      color: #1976d2;
    }}
    .card.matched {{
      background: #c8e6c9;
      border-color: #4caf50;
      color: #2e7d32;
    }}
    .status {{
      text-align: center;
      margin-bottom: 16px;
    }}
    .status p {{
      margin: 8px 0;
      color: #555;
      font-size: 16px;
    }}
    .reset-btn {{
      display: block;
      width: 100%;
      padding: 12px;
      margin-top: 8px;
      background: #667eea;
      color: white;
      border: none;
      border-radius: 6px;
      font-size: 16px;
      font-weight: bold;
      cursor: pointer;
      transition: background 0.2s ease;
    }}
    .reset-btn:hover {{
      background: #764ba2;
    }}
  </style>
</head>
<body>
{canvas_html}
{root_html}
  <script>
{self._result.js}
  </script>
</body>
</html>
"""

    def _stmt_to_js(self, stmt: IRNode, indent: int) -> str:
        pad = "  " * indent
        if isinstance(stmt, IRReturnStatement):
            if stmt.value is None:
                return f"{pad}return;"
            return f"{pad}return {self._expr_to_js(stmt.value)};"
        if isinstance(stmt, IRIfStatement):
            return self._if_to_js(stmt, indent)
        if isinstance(stmt, IRForLoop):
            return self._for_to_js(stmt, indent)
        if isinstance(stmt, IRExprStatement):
            return f"{pad}{self._expr_to_js(stmt.expression)};"
        if isinstance(stmt, IRCallExpr):
            return f"{pad}{self._expr_to_js(stmt)};"
        if isinstance(stmt, IRAwaitExpr):
            return f"{pad}{self._expr_to_js(stmt)};"
        if hasattr(stmt, "target") and hasattr(stmt, "value"):
            return self._assignment_to_js(stmt, indent)
        return f"{pad}// unsupported {type(stmt).__name__}"

    def _assignment_to_js(self, stmt: IRNode, indent: int) -> str:
        pad = "  " * indent
        target = getattr(stmt, "target", None)
        value = getattr(stmt, "value", None)
        if isinstance(target, IRIndexAccess):
            signal_name = self._signal_name(target.obj)
            index = self._expr_to_js(target.index)
            rendered = self._expr_to_js(value)
            if signal_name:
                return (
                    f"{pad}_engine.get('{signal_name}').setIndex({index}, {rendered});"
                )
            obj = self._expr_to_js(target.obj)
            return f"{pad}{obj}[{index}] = {rendered};"
        if isinstance(target, IRIdentifier):
            rendered = self._expr_to_js(value)
            if target.name in self._signal_names:
                return f"{pad}_engine.get('{target.name}').set({rendered});"
            return f"{pad}{target.name} = {rendered};"
        rendered_target = self._expr_to_js(target)
        rendered_value = self._expr_to_js(value)
        return f"{pad}{rendered_target} = {rendered_value};"

    def _if_to_js(self, node: IRIfStatement, indent: int) -> str:
        pad = "  " * indent
        lines = [f"{pad}if ({self._expr_to_js(node.condition)}) {{"]
        lines.extend(self._stmt_to_js(stmt, indent + 1) for stmt in (node.body or []))
        lines.append(f"{pad}}}")
        for clause in (node.elif_clauses or []):
            lines.append(f"{pad}else if ({self._expr_to_js(clause.condition)}) {{")
            lines.extend(
                self._stmt_to_js(stmt, indent + 1) for stmt in (clause.body or [])
            )
            lines.append(f"{pad}}}")
        if node.else_body:
            lines.append(f"{pad}else {{")
            lines.extend(
                self._stmt_to_js(stmt, indent + 1) for stmt in (node.else_body or [])
            )
            lines.append(f"{pad}}}")
        return "\n".join(lines)

    def _for_to_js(self, node: IRForLoop, indent: int) -> str:
        pad = "  " * indent
        target = self._identifier_name(node.target) or "i"
        iterable = node.iterable
        if isinstance(iterable, IRCallExpr) and self._call_name(iterable.func) == "range":
            args = iterable.args or []
            if len(args) == 1:
                start, stop, step = "0", self._expr_to_js(args[0]), "1"
            elif len(args) == 2:
                start = self._expr_to_js(args[0])
                stop = self._expr_to_js(args[1])
                step = "1"
            else:
                start = self._expr_to_js(args[0])
                stop = self._expr_to_js(args[1])
                step = self._expr_to_js(args[2])
            lines = [
                f"{pad}for (let {target} = {start}; {target} < {stop}; {target} += {step}) {{"
            ]
            lines.extend(self._stmt_to_js(stmt, indent + 1) for stmt in (node.body or []))
            lines.append(f"{pad}}}")
            return "\n".join(lines)
        iterable_js = self._expr_to_js(iterable)
        lines = [f"{pad}for (const {target} of {iterable_js}) {{"]
        lines.extend(self._stmt_to_js(stmt, indent + 1) for stmt in (node.body or []))
        lines.append(f"{pad}}}")
        return "\n".join(lines)

    def _element_to_js(self, elem: IRUIElement, parent_var: str, indent: int) -> list[str]:
        pad = "  " * indent
        lines: list[str] = []
        if elem.condition is not None:
            lines.append(f"{pad}if ({self._expr_to_js(elem.condition)}) {{")
            lines.extend(self._element_to_js_unconditional(elem, parent_var, indent + 1))
            lines.append(f"{pad}}}")
            return lines
        return self._element_to_js_unconditional(elem, parent_var, indent)

    def _element_to_js_unconditional(
        self, elem: IRUIElement, parent_var: str, indent: int
    ) -> list[str]:
        pad = "  " * indent
        var_name = f"__el_{abs(id(elem))}"
        lines = [f"{pad}const {var_name} = document.createElement('{elem.tag or 'div'}');"]

        for attr in (elem.attributes or []):
            value = self._expr_to_js(attr.value)
            if attr.name == "class" and not attr.is_class_binding:
                lines.append(f"{pad}{var_name}.className = {value};")
            elif attr.is_class_binding:
                class_name = attr.name.split(":", 1)[1] if ":" in attr.name else attr.name
                lines.append(
                    f"{pad}if ({value}) {{ {var_name}.classList.add('{class_name}'); }}"
                )
            elif attr.name == "disabled":
                lines.append(f"{pad}{var_name}.disabled = {value};")
            elif attr.is_event_handler:
                lines.append(
                    f"{pad}{var_name}.addEventListener('click', async () => {{ {value}; }});"
                )
            else:
                lines.append(f"{pad}{var_name}.setAttribute('{attr.name}', {value});")

        if elem.text_content is not None:
            lines.append(f"{pad}{var_name}.textContent = {self._expr_to_js(elem.text_content)};")

        for child in (elem.children or []):
            lines.extend(self._render_child(child, var_name, indent))

        lines.append(f"{pad}{parent_var}.appendChild({var_name});")
        return lines

    def _render_child(self, child: IRNode, parent_var: str, indent: int) -> list[str]:
        pad = "  " * indent
        if isinstance(child, IRUIElement):
            return self._element_to_js(child, parent_var, indent)
        if isinstance(child, IRForLoop):
            return [self._for_render_to_js(child, parent_var, indent)]
        if isinstance(child, IRIfStatement):
            return [self._if_render_to_js(child, parent_var, indent)]
        if isinstance(child, IRExprStatement):
            if isinstance(child.expression, IRCallExpr):
                if self._call_name(child.expression.func) == "memory_game":
                    return []
            value = self._expr_to_js(child.expression)
            return [f"{pad}{parent_var}.appendChild(document.createTextNode(String({value})));"]
        if isinstance(child, (IRLiteral, IRCallExpr, IRIdentifier, IRBinaryOp, IRConditionalExpr)):
            value = self._expr_to_js(child)
            return [f"{pad}{parent_var}.appendChild(document.createTextNode(String({value})));"]
        return [f"{pad}// unsupported child {type(child).__name__}"]

    def _if_render_to_js(self, node: IRIfStatement, parent_var: str, indent: int) -> str:
        pad = "  " * indent
        lines = [f"{pad}if ({self._expr_to_js(node.condition)}) {{"]
        for stmt in (node.body or []):
            lines.extend(self._render_child(stmt, parent_var, indent + 1))
        lines.append(f"{pad}}}")
        for clause in (node.elif_clauses or []):
            lines.append(f"{pad}else if ({self._expr_to_js(clause.condition)}) {{")
            for stmt in (clause.body or []):
                lines.extend(self._render_child(stmt, parent_var, indent + 1))
            lines.append(f"{pad}}}")
        if node.else_body:
            lines.append(f"{pad}else {{")
            for stmt in (node.else_body or []):
                lines.extend(self._render_child(stmt, parent_var, indent + 1))
            lines.append(f"{pad}}}")
        return "\n".join(lines)

    def _for_render_to_js(self, node: IRForLoop, parent_var: str, indent: int) -> str:
        pad = "  " * indent
        target = self._identifier_name(node.target) or "i"
        iterable = node.iterable
        lines: list[str] = []
        if isinstance(iterable, IRCallExpr) and self._call_name(iterable.func) == "range":
            args = iterable.args or []
            if len(args) == 1:
                start, stop, step = "0", self._expr_to_js(args[0]), "1"
            elif len(args) == 2:
                start = self._expr_to_js(args[0])
                stop = self._expr_to_js(args[1])
                step = "1"
            else:
                start = self._expr_to_js(args[0])
                stop = self._expr_to_js(args[1])
                step = self._expr_to_js(args[2])
            lines.append(
                f"{pad}for (let {target} = {start}; {target} < {stop}; {target} += {step}) {{"
            )
        else:
            iterable_js = self._expr_to_js(iterable)
            lines.append(f"{pad}for (const {target} of {iterable_js}) {{")
        for stmt in (node.body or []):
            lines.extend(self._render_child(stmt, parent_var, indent + 1))
        lines.append(f"{pad}}}")
        return "\n".join(lines)

    def _expr_to_js(self, node: IRNode | None) -> str:
        if node is None:
            return "null"
        if isinstance(node, IRLiteral):
            if node.kind == "string":
                return repr(str(node.value))
            if node.kind == "bool":
                return "true" if bool(node.value) else "false"
            if node.kind == "none":
                return "null"
            return str(node.value)
        if isinstance(node, IRListLiteral):
            return "[" + ", ".join(self._expr_to_js(item) for item in node.elements) + "]"
        if isinstance(node, IRIdentifier):
            if node.name in self._signal_names:
                return f"_engine.get('{node.name}').get()"
            return node.name
        if isinstance(node, IRIndexAccess):
            return f"{self._expr_to_js(node.obj)}[{self._expr_to_js(node.index)}]"
        if isinstance(node, IRAttributeAccess):
            return f"{self._expr_to_js(node.obj)}.{node.attr}"
        if isinstance(node, IRBinaryOp):
            return f"({self._expr_to_js(node.left)} {node.op} {self._expr_to_js(node.right)})"
        if isinstance(node, IRBooleanOp):
            op = " && " if node.op == "and" else " || "
            return "(" + op.join(self._expr_to_js(value) for value in node.values) + ")"
        if isinstance(node, IRCompareOp):
            left = self._expr_to_js(node.left)
            parts: list[str] = []
            current_left = left
            for op, right in node.comparators:
                right_js = self._expr_to_js(right)
                parts.append(f"({current_left} {op} {right_js})")
                current_left = right_js
            return " && ".join(parts) if parts else left
        if isinstance(node, IRUnaryOp):
            if node.op == "not":
                return f"(!{self._expr_to_js(node.operand)})"
            return f"({node.op}{self._expr_to_js(node.operand)})"
        if isinstance(node, IRConditionalExpr):
            return (
                f"({self._expr_to_js(node.condition)}"
                f" ? {self._expr_to_js(node.true_expr)}"
                f" : {self._expr_to_js(node.false_expr)})"
            )
        if isinstance(node, IRCallExpr):
            call_name = self._call_name(node.func)
            args = ", ".join(self._expr_to_js(arg) for arg in (node.args or []))
            if call_name == "str":
                return f"String({args})"
            if call_name == "len":
                return f"({self._expr_to_js(node.args[0])}).length" if node.args else "0"
            if call_name == "asyncio.sleep":
                delay = self._expr_to_js(node.args[0]) if node.args else "0"
                return f"new Promise((resolve) => setTimeout(resolve, {delay} * 1000))"
            func_js = self._expr_to_js(node.func)
            return f"{func_js}({args})"
        if isinstance(node, IRAwaitExpr):
            return f"await {self._expr_to_js(node.value)}"
        return f"null /* {type(node).__name__} */"

    def _identifier_name(self, node: IRNode | None) -> str | None:
        return node.name if isinstance(node, IRIdentifier) else None

    def _signal_name(self, node: IRNode | None) -> str | None:
        if isinstance(node, IRIdentifier):
            return node.name
        return None

    def _call_name(self, node: IRNode | None) -> str | None:
        if isinstance(node, IRIdentifier):
            return node.name
        if isinstance(node, IRAttributeAccess):
            base = self._call_name(node.obj)
            if base:
                return f"{base}.{node.attr}"
        return None


def lower_to_ui(program: IRProgram) -> UILoweringResult:
    """Lower an IRProgram to a browser preview bundle."""
    return UILoweringPass().lower(program)
