#
# SPDX-FileCopyrightText: 2026 John Samuel <johnsamuelwrites@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""Core 1.0 UI lowering pass — full reactive JavaScript generation.

Transforms reactive IR nodes into a complete, self-contained JavaScript bundle
with inline ReactiveSignal/ReactiveList runtime, async game functions, and
reactive DOM rendering.

This module generates a single HTML page that can be deployed to GitHub Pages
with zero external dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from multilingualprogramming.core.ir_nodes import (
    IRAwaitExpr,
    IRBinaryOp,
    IRBooleanOp,
    IRBooleanLiteral,
    IRCallExpr,
    IRCanvasBlock,
    IRCompareOp,
    IRConditionalExpr,
    IRForLoop,
    IRFunction,
    IRIdentifier,
    IRIfStatement,
    IRIndexAccess,
    IRLiteral,
    IRListLiteral,
    IRNode,
    IRObserveBinding,
    IROnChange,
    IRProgram,
    IRRenderBlock,
    IRRenderExpr,
    IRReturnStatement,
    IRUnaryOp,
    IRUIAttribute,
    IRUIElement,
    IRViewBinding,
)


@dataclass
class UILoweringResult:
    """Output of the UI lowering pass — a complete self-contained JS bundle."""

    html: str = ""  # The complete HTML page
    js: str = ""    # The bundled JavaScript
    diagnostics: list[str] = field(default_factory=list)

    def emit_html(self) -> str:
        """Return the complete HTML document."""
        return self.html

    def emit_js(self) -> str:
        """Return just the JavaScript bundle (for inspection)."""
        return self.js


class UILoweringPass:
    """Lower an IRProgram into a complete reactive JavaScript bundle."""

    def __init__(self) -> None:
        self._result = UILoweringResult()
        self._signal_names: list[str] = []
        self._js_preamble = ""
        self._js_signals = []
        self._js_functions = []
        self._js_render_fn = ""
        self._js_signal_listeners = []
        self._js_init = ""
        self._ast_async_depth = 0

    def lower(self, program: IRProgram) -> UILoweringResult:
        """Lower an IRProgram to JS+HTML output."""
        # Collect signal names and emit JS preamble
        self._emit_preamble()

        # Process program body
        for node in program.body:
            if isinstance(node, IRObserveBinding):
                self._lower_observe(node)
            elif isinstance(node, IRFunction):
                self._lower_function(node)
            elif isinstance(node, IRRenderBlock):
                self._lower_render_block(node)

        # Wire reactive updates
        self._generate_reactive_wiring()

        # Assemble complete JS
        js_parts = [self._js_preamble]
        js_parts.extend(self._js_signals)
        js_parts.extend(self._js_functions)
        if self._js_render_fn:
            js_parts.append(self._js_render_fn)
        js_parts.extend(self._js_signal_listeners)
        if self._js_init:
            js_parts.append(self._js_init)

        self._result.js = "\n\n".join(js_parts)

        # Generate HTML wrapper
        self._result.html = self._generate_html_wrapper()

        return self._result

    def _emit_preamble(self) -> None:
        """Emit the reactive runtime and setup code."""
        self._js_preamble = '''// Generated by Multilingual 1.0 UI lowering pass
// Self-contained reactive JavaScript bundle (no external dependencies)

// Inline ReactiveSignal class
class ReactiveSignal {
  constructor(value) {
    this._value = value;
    this._handlers = [];
  }
  get() {
    return this._value;
  }
  set(v) {
    this._value = v;
    this._notify();
  }
  on_change(h) {
    this._handlers.push(h);
  }
  _notify() {
    for (const h of this._handlers) {
      h(this._value);
    }
  }
}

// Inline ReactiveList class
class ReactiveList {
  constructor(value) {
    this._value = Array.from(value);
    this._handlers = [];
  }
  get() {
    return this._value.slice();
  }
  set(v) {
    this._value = Array.from(v);
    this._notify();
  }
  setIndex(i, v) {
    this._value[i] = v;
    this._notify();
  }
  on_change(h) {
    this._handlers.push(h);
  }
  _notify() {
    for (const h of this._handlers) {
      h(this._value.slice());
    }
  }
}

// Signal factory
function __ml_signal(initial) {
  return Array.isArray(initial) ? new ReactiveList(initial) : new ReactiveSignal(initial);
}

// Global signals store
const __ml_signals = {};
'''

    def _lower_observe(self, node: IRObserveBinding) -> None:
        """Emit a signal declaration."""
        self._signal_names.append(node.name)
        val = self._expr_to_js(node.value)
        sig_init = f"__ml_signals['{node.name}'] = __ml_signal({val});"
        self._js_signals.append(sig_init)

    def _lower_function(self, node: IRFunction) -> None:
        """Emit an async function."""
        if not node.is_async:
            return  # Only emit async functions
        params = ", ".join(p.name for p in (node.parameters or []))
        body = self._function_body_to_js(node.body)
        func = f"async function {node.name}({params}) {{\n{body}\n}}"
        self._js_functions.append(func)

    def _function_body_to_js(self, body: list[IRNode]) -> str:
        """Convert a function body (list of statements) to JS."""
        lines = []
        for stmt in body:
            if isinstance(stmt, IRReturnStatement):
                if stmt.value:
                    val = self._expr_to_js(stmt.value)
                    lines.append(f"  return {val};")
                else:
                    lines.append("  return;")
            elif isinstance(stmt, IRIfStatement):
                lines.append(self._if_statement_to_js(stmt))
            elif isinstance(stmt, IRForLoop):
                lines.append(self._for_loop_to_js(stmt))
            else:
                # Generic statement (assignment, expression)
                if hasattr(stmt, 'target') and hasattr(stmt, 'value'):
                    # Assignment
                    target = stmt.target
                    if isinstance(target, IRIndexAccess):
                        # List index assignment
                        obj_name = target.obj.name if isinstance(target.obj, IRIdentifier) else None
                        if obj_name:
                            idx = self._expr_to_js(target.index)
                            val = self._expr_to_js(stmt.value)
                            lines.append(f"  __ml_signals['{obj_name}'].setIndex({idx}, {val});")
                        else:
                            lines.append(f"  // Complex assignment (unsupported in JS output)")
                    else:
                        # Scalar assignment
                        tgt = self._expr_to_js(target)
                        val = self._expr_to_js(stmt.value)
                        if isinstance(target, IRIdentifier):
                            lines.append(f"  __ml_signals['{target.name}'].set({val});")
                        else:
                            lines.append(f"  {tgt} = {val};")
                else:
                    # Expression statement
                    if isinstance(stmt, IRCallExpr):
                        expr = self._expr_to_js(stmt)
                        lines.append(f"  {expr};")
        return "\n".join(lines)

    def _if_statement_to_js(self, node: IRIfStatement) -> str:
        """Convert an if statement to JS."""
        cond = self._expr_to_js(node.condition)
        lines = [f"  if ({cond}) {{"]
        for stmt in node.body:
            lines.append(self._stmt_to_js(stmt))
        lines.append("  }")
        for elif_clause in (getattr(node, 'elif_clauses', None) or []):
            elif_cond = self._expr_to_js(elif_clause.condition)
            lines.append(f"  else if ({elif_cond}) {{")
            for stmt in elif_clause.body:
                lines.append(self._stmt_to_js(stmt))
            lines.append("  }")
        if getattr(node, 'else_body', None):
            lines.append("  else {")
            for stmt in node.else_body:
                lines.append(self._stmt_to_js(stmt))
            lines.append("  }")
        return "\n".join(lines)

    def _for_loop_to_js(self, node: IRForLoop) -> str:
        """Convert a for loop to JS."""
        # Assuming range-based loop
        target = node.target.name if isinstance(node.target, IRIdentifier) else "i"
        if isinstance(node.iter, IRCallExpr) and isinstance(node.iter.func, IRIdentifier):
            if node.iter.func.name == "range":
                # range(n) loop
                if len(node.iter.args) == 1:
                    n = self._expr_to_js(node.iter.args[0])
                    lines = [f"  for (let {target} = 0; {target} < {n}; {target}++) {{"]
                else:
                    # range(start, stop) or range(start, stop, step)
                    start = self._expr_to_js(node.iter.args[0]) if len(node.iter.args) > 0 else "0"
                    stop = self._expr_to_js(node.iter.args[1]) if len(node.iter.args) > 1 else "0"
                    step = self._expr_to_js(node.iter.args[2]) if len(node.iter.args) > 2 else "1"
                    lines = [f"  for (let {target} = {start}; {target} < {stop}; {target} += {step}) {{"]
                for stmt in node.body:
                    lines.append(self._stmt_to_js(stmt))
                lines.append("  }")
                return "\n".join(lines)
        return f"  // for loop not supported"

    def _stmt_to_js(self, stmt: IRNode) -> str:
        """Convert a single statement to indented JS line."""
        if isinstance(stmt, IRReturnStatement):
            if stmt.value:
                val = self._expr_to_js(stmt.value)
                return f"    return {val};"
            else:
                return "    return;"
        elif hasattr(stmt, 'target') and hasattr(stmt, 'value'):
            target = stmt.target
            if isinstance(target, IRIndexAccess):
                obj_name = target.obj.name if isinstance(target.obj, IRIdentifier) else None
                if obj_name:
                    idx = self._expr_to_js(target.index)
                    val = self._expr_to_js(stmt.value)
                    return f"    __ml_signals['{obj_name}'].setIndex({idx}, {val});"
            elif isinstance(target, IRIdentifier):
                val = self._expr_to_js(stmt.value)
                return f"    __ml_signals['{target.name}'].set({val});"
        return "    // statement"

    def _lower_render_block(self, node: IRRenderBlock) -> None:
        """Generate the reactive __ml_render() function from a render: block."""
        if not node.root:
            return

        # Build the render function
        render_lines = ["function __ml_render() {"]

        # Find the target container (usually "board" or similar)
        target_id = getattr(node.root, 'tag', '') + "_container"
        if hasattr(node.root, 'attributes'):
            for attr in node.root.attributes:
                if attr.name == 'id':
                    target_id = self._expr_to_js(attr.value).strip('"\'')
                    break

        # Clear and rebuild the DOM
        render_lines.append(f"  const __container = document.getElementById('{target_id}');")
        render_lines.append(f"  if (!__container) return;")
        render_lines.append(f"  __container.innerHTML = '';")

        # Recursively generate element creation code
        element_code = self._element_to_js(node.root, "__container")
        render_lines.append(element_code)

        render_lines.append("}")
        self._js_render_fn = "\n".join(render_lines)

    def _element_to_js(self, elem: IRUIElement, parent_var: str, indent: int = 1) -> str:
        """Generate JS code to create a UI element and its children."""
        ind = "  " * indent
        ind2 = "  " * (indent + 1)
        lines = []

        elem_var = f"__el_{id(elem)}"
        tag = elem.tag or "div"
        lines.append(f"{ind}const {elem_var} = document.createElement('{tag}');")

        # Set static class
        classes = []
        for attr in (elem.attributes or []):
            if attr.name == "class" and not attr.is_class_binding:
                classes.append(self._expr_to_js(attr.value).strip('"\''))
        if classes:
            lines.append(f"{ind}{elem_var}.className = '{' '.join(classes)}';")

        # Set conditional classes and other attributes
        for attr in (elem.attributes or []):
            if attr.name.startswith("class:"):
                class_name = attr.name[6:]  # Strip "class:"
                expr = self._expr_to_js(attr.value)
                lines.append(f"{ind}if ({expr}) {elem_var}.classList.add('{class_name}');")
            elif attr.name == "disabled":
                expr = self._expr_to_js(attr.value)
                lines.append(f"{ind}{elem_var}.disabled = {expr};")
            elif attr.is_event_handler and attr.name == "onclick":
                # Extract function call
                handler_code = self._expr_to_js(attr.value)
                lines.append(f"{ind}{elem_var}.addEventListener('click', async () => {{\n{ind2}{handler_code};\n{ind}}});")
            elif not attr.is_class_binding and attr.name not in ("class", "disabled"):
                # Other attributes
                val = self._expr_to_js(attr.value)
                lines.append(f"{ind}{elem_var}.setAttribute('{attr.name}', {val});")

        # Handle text content (simple case)
        if elem.text_content:
            text = self._expr_to_js(elem.text_content)
            lines.append(f"{ind}{elem_var}.textContent = {text};")

        # Handle children
        if elem.children:
            for child in elem.children:
                if isinstance(child, IRUIElement):
                    child_code = self._element_to_js(child, elem_var, indent + 1)
                    lines.append(child_code)
                    child_var = f"__el_{id(child)}"
                    lines.append(f"{ind}{elem_var}.appendChild({child_var});")
                elif isinstance(child, IRIfStatement):
                    # Conditional child rendering
                    lines.append(self._conditional_child_to_js(child, elem_var, indent))
                elif isinstance(child, IRForLoop):
                    # Loop to generate children
                    lines.append(self._loop_children_to_js(child, elem_var, indent))

        # Append to parent
        lines.append(f"{ind}{parent_var}.appendChild({elem_var});")

        return "\n".join(lines)

    def _conditional_child_to_js(self, cond: IRIfStatement, parent_var: str, indent: int) -> str:
        """Generate conditional child rendering."""
        ind = "  " * indent
        lines = [f"{ind}if ({self._expr_to_js(cond.condition)}) {{"]
        for child in cond.body:
            if isinstance(child, IRUIElement):
                child_code = self._element_to_js(child, parent_var, indent + 1)
                lines.append(child_code)
        lines.append(f"{ind}}}")
        return "\n".join(lines)

    def _loop_children_to_js(self, loop: IRForLoop, parent_var: str, indent: int) -> str:
        """Generate children from a loop inside render."""
        ind = "  " * indent
        lines = []

        target = loop.target.name if isinstance(loop.target, IRIdentifier) else "i"
        if isinstance(loop.iter, IRCallExpr) and isinstance(loop.iter.func, IRIdentifier):
            if loop.iter.func.name == "range":
                if len(loop.iter.args) == 1:
                    n = self._expr_to_js(loop.iter.args[0])
                    lines.append(f"{ind}for (let {target} = 0; {target} < {n}; {target}++) {{")

                    for stmt in loop.body:
                        if isinstance(stmt, IRUIElement):
                            elem_code = self._element_to_js(stmt, parent_var, indent + 1)
                            lines.append(elem_code)

                    lines.append(f"{ind}}}")

        return "\n".join(lines)

    def _expr_to_js(self, node: IRNode | None) -> str:
        """Convert IR expressions to JavaScript."""
        if node is None:
            return "null"

        if isinstance(node, IRLiteral):
            if node.kind == "string":
                return repr(str(node.value))
            elif node.kind == "bool":
                return "true" if node.value else "false"
            elif node.kind in ("int", "float"):
                return str(node.value)
            else:
                return str(node.value)

        if isinstance(node, IRListLiteral):
            elements = [self._expr_to_js(e) for e in (node.elements or [])]
            return f"[{', '.join(elements)}]"

        if isinstance(node, IRIdentifier):
            # Check if this is a signal reference (read)
            if node.name in self._signal_names:
                return f"__ml_signals['{node.name}'].get()"
            return node.name

        if isinstance(node, IRIndexAccess):
            obj = self._expr_to_js(node.obj)
            idx = self._expr_to_js(node.index)
            # Remove the .get() if present
            if obj.endswith(".get()"):
                return f"{obj[:-6]}()[{idx}]"
            return f"{obj}[{idx}]"

        if isinstance(node, IRBinaryOp):
            left = self._expr_to_js(node.left)
            right = self._expr_to_js(node.right)
            return f"({left} {node.op} {right})"

        if isinstance(node, IRCompareOp):
            left = self._expr_to_js(node.left)
            right = self._expr_to_js(node.right)
            return f"({left} {node.op} {right})"

        if isinstance(node, IRBooleanOp):
            op = "&&" if node.op == "and" else "||"
            left = self._expr_to_js(node.left)
            right = self._expr_to_js(node.right)
            return f"({left} {op} {right})"

        if isinstance(node, IRUnaryOp):
            if node.op == "not":
                return f"(!{self._expr_to_js(node.operand)})"
            return f"({node.op}{self._expr_to_js(node.operand)})"

        if isinstance(node, IRCallExpr):
            func_name = None
            if isinstance(node.func, IRIdentifier):
                func_name = node.func.name

            if func_name == "asyncio.sleep":
                if node.args:
                    duration = self._expr_to_js(node.args[0])
                    return f"new Promise(r => setTimeout(r, {duration} * 1000))"
                return f"new Promise(r => setTimeout(r, 1000))"
            elif func_name in ("str", "String"):
                if node.args:
                    return f"String({self._expr_to_js(node.args[0])})"
                return "''"
            elif func_name == "range":
                # For use in expressions (shouldn't happen, but handle it)
                if len(node.args) == 1:
                    n = self._expr_to_js(node.args[0])
                    return f"Array.from({{length: {n}}}, (_, i) => i)"
                return "[]"
            elif func_name == "len":
                if node.args:
                    obj = self._expr_to_js(node.args[0])
                    return f"{obj}.length"
                return "0"
            else:
                # Generic function call
                args = ", ".join(self._expr_to_js(arg) for arg in (node.args or []))
                return f"{func_name}({args})"

        if isinstance(node, IRAwaitExpr):
            # await asyncio.sleep(t) -> await new Promise(...)
            if isinstance(node.value, IRCallExpr):
                return f"await {self._expr_to_js(node.value)}"
            return f"await {self._expr_to_js(node.value)}"

        if isinstance(node, IRConditionalExpr):
            cond = self._expr_to_js(node.condition)
            then_val = self._expr_to_js(node.body)
            else_val = self._expr_to_js(node.else_body)
            return f"({cond} ? {then_val} : {else_val})"

        if isinstance(node, IRIfStatement):
            # This shouldn't happen in pure expression context
            return "null"

        # Fallback
        return f"/* {type(node).__name__} */"

    def _generate_reactive_wiring(self) -> None:
        """Wire signal change listeners to trigger re-render."""
        if not self._signal_names:
            return

        wiring_lines = []
        for sig_name in self._signal_names:
            wiring_lines.append(
                f"__ml_signals['{sig_name}'].on_change(() => __ml_render());"
            )

        self._js_signal_listeners = wiring_lines

    def _generate_html_wrapper(self) -> str:
        """Generate the complete HTML document."""
        return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memory Game - Multilingual</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }}
        .game-container {{
            background: white;
            border-radius: 16px;
            padding: 40px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            max-width: 600px;
            width: 100%;
        }}
        h1 {{
            text-align: center;
            color: #667eea;
            margin-bottom: 10px;
            font-size: 2em;
        }}
        .subtitle {{
            text-align: center;
            color: #999;
            margin-bottom: 30px;
            font-size: 0.9em;
        }}
        .game-board {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-bottom: 20px;
        }}
        .card {{
            aspect-ratio: 1;
            border: 2px solid #667eea;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            font-size: 1.8em;
            font-weight: bold;
            cursor: pointer;
            border-radius: 8px;
            transition: all 0.3s ease;
            display: flex;
            align-items: center;
            justify-content: center;
        }}
        .card:hover:not(:disabled) {{
            transform: translateY(-4px);
            box-shadow: 0 8px 20px rgba(102, 126, 234, 0.4);
        }}
        .card:disabled {{
            cursor: not-allowed;
            opacity: 0.7;
        }}
        .card.revealed {{
            background: linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%);
            color: #333;
        }}
        .card.matched {{
            background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
            color: white;
        }}
        .status {{
            text-align: center;
            background: #f0f4ff;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 15px;
            min-height: 60px;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }}
        .status p {{
            color: #333;
            font-size: 1em;
            margin: 5px 0;
        }}
        .status .win {{
            color: #fa709a;
            font-size: 1.3em;
            font-weight: bold;
        }}
        .reset-btn {{
            width: 100%;
            padding: 12px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 1em;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s ease;
        }}
        .reset-btn:hover {{
            transform: translateY(-2px);
            box-shadow: 0 8px 20px rgba(102, 126, 234, 0.4);
        }}
    </style>
</head>
<body>
    <div class="game-container">
        <h1>🎮 Memory Game</h1>
        <p class="subtitle">Written in Multilingual • Compiled to JavaScript</p>

        <div class="game-board" id="game_board_container"></div>

        <div class="status" id="status_container">
            <p>Matches: <span id="matches">0</span> / 4</p>
        </div>

        <button class="reset-btn" onclick="reset_game()">New Game</button>
    </div>

    <script>
{self._result.js}

// Initial render
__ml_render();
    </script>
</body>
</html>
'''


def lower_to_ui(program: IRProgram) -> UILoweringResult:
    """Lower an IRProgram to reactive UI output."""
    return UILoweringPass().lower(program)
